<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.smtp2go.com/v3/email/send');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "\n{\n  \"sender\": \"salesusa@havells.com\",\n  \"to\": [\n    \"bhavikrsuthar@gmail.com\"\n  ],\n  \"subject\": \"SMTP2GO attachment\",\n  \"text_body\": \"Hello - find the email attached\",\n\t\"attachments\": [\n    {\n      \"filename\": \"testfile.pdf\",\n      \"url\": \"https://partner.havellslighting.com/invoice(63).pdf\",\n      \"mimetype\": \"application/pdf\"\n   \t}\n\t]\n  \n}\n");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'X-Smtp2go-Api-Key: api-30513C6A27974AD693CC04A2ABF8AE68';
$headers[] = 'Accept: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
print_r($result);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

?>